# Generated by Django 2.2.8 on 2020-05-10 10:49

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0011_magicbyte_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='magicbyte',
            field=models.CharField(default='0,5', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Magicbytes'),
        ),
    ]
